data: # root path of train/validation data (either relative/absoulte path is ok)
  input_wavs: 'data\wavs'
  output_wavs: 'data\clean'
  mel_path: 'data\mels'
---
train:
  seed: 1234
  num_gpus: 1
  rep_discriminator: 2
  discriminator_train_start_steps: 1000000
  postnet_start_steps: 500000
  num_workers: 4
  batch_size: 2
  optimizer: 'adam'
  adamG:
    lr: 0.001
    beta1: 0.5
    beta2: 0.9
    lr_decay: 0.999
  adamD:
    lr: 0.001
    beta1: 0.5
    beta2: 0.9


---
dist:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1

---
audio:
  n_mel_channels: 80
  segment_length: 32000
  pad_short: 2000
  filter_length: 1024
  hop_length: 256 # WARNING: this can't be changed.
  win_length: 1024
  sampling_rate: 22050
  mel_fmin: 0.0
  mel_fmax: 8000.0
  fmax_for_loss: null
---
model:
  feat_match: 10.0
  lambda_adv: 2.5
  lambda_time_loss: 20
  use_subband_stft_loss: False
  feat_loss: False
  out_channels: 1
  in_channels: 1 # 32 or 1
  num_layers: 20
  num_stacks: 2
  kernel_size: 3
  residual_channels: 128
  gate_channels: 128
  skip_out_channels: 128
  num_D : 3
  ndf : 16
  n_layers: 3
  downsampling_factor: 4
  disc_out: 512

stft_loss_params:
    fft_sizes: [1024, 2048, 512]  # List of FFT size for STFT-based loss.
    hop_sizes: [120, 240, 50]     # List of hop size for STFT-based loss
    win_lengths: [600, 1200, 240] # List of window length for STFT-based loss.
    window: "hann_window"         # Window function for STFT-based loss

---
logs:
  summary_interval: 100
  validation_interval: 1000
  save_interval: 5000
  chkpt_dir: 'chkpt'
  log_dir: 'logs'